# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Documentation

permissions:
  contents: write
  pages: write
  pull-requests: write
  id-token: write

on:
  pull_request_target:
    types: [opened, reopened, synchronize] # Allows forks to trigger the docs build
  push:
    branches:
      - main
  merge_group:
    types: [checks_requested]

jobs:
  build-docs:
    uses: eclipse-score/cicd-workflows/.github/workflows/docs.yml@main
    permissions:
      contents: write
      pages: write
      pull-requests: write
      id-token: write

    with:
      bazel-target: "//docs:github_pages__release --define github_user=eclipse-score --define github_repo=docs-as-code"
      retention-days: 3
